### ISSUE TITLE
`The URL to download the Developer Disk image could not be determined` when trying to enable JIT on iOS17

### ISSUE THREAD

**Issue by hscumbie** [rileytestut/AltStore#1349]
I am using **macOS 12.7.1 (Monterey)** with an **iPhone 14 Pro Max on iOS 17.1.2.** I am currently getting the error attached below when trying to enable JIT over USB with AltServer. I have a hunch that it has to do with macOS 12.7.1 not being Xcode 15 compatible (which is needed for iOS 17 development). I wasn't sure if there is a work around, or if macOS 12.7.1 needed to be labeled as "incompatible" for JIT on iOS17.
![Screen Shot 2023-12-07 at 8 38 04 PM](https://github.com/altstoreio/AltStore/assets/93226094/d82abab4-3eb7-49a1-b0b4-4c57903ca822)

**Comment by shanegillio** [comment]
is this the latest version of AltServer?

**Comment by hscumbie** [comment]
I'm using `AltServer 1.7.1`. I tried getting an update but it failed. It looks like the `altstore.io` website is currently down...

![Screen Shot 2023-12-12 at 3 35 48 PM](https://github.com/altstoreio/AltStore/assets/93226094/fb5f0c23-7933-424c-8831-effc72acd258)

**Comment by shanegillio** [comment]
Fixed the website issues if you want to try again

**Comment by hscumbie** [comment]
It looks like `1.7.1` is the latest version unless something still isn't right with the software updater.

![Screen Shot 2023-12-13 at 3 53 14 PM](https://github.com/altstoreio/AltStore/assets/93226094/27a42702-1836-4647-8a56-9aa222907fa6)

**Comment by ZDStudios** [comment]
help meeeeeeee

**Comment by hscumbie** [comment]
I finally found a fix for those of us stuck on MacOS 12 or earlier with iOS17 devices! I was able to successfully enable JIT by creating a Ventura virtual machine using VMware Fusion. After following the steps on the AltStore website, it works perfectly! I will hopefully get a YouTube video of the entire process made and posted soon.

**Comment by Beginningwithn** [comment]
> I finally found a fix for those of us stuck on MacOS 12 or earlier with iOS17 devices! I was able to successfully enable JIT by creating a Ventura virtual machine using VMware Fusion. After following the steps on the AltStore website, it works perfectly! I will hopefully get a YouTube video of the entire process made and posted soon.

Any chance you could give me an update? I'm on catalina so i can only run vmware 11. It wont let me install anything higher than 10.15, which im running. I assume you are on 11 or 12 already?

**Comment by Namiothe5th** [comment]
Hi! I just wanted to ask if you ever made that YouTube video by chance? I'm having the same problem and it sounds like you have a really good step-by-step guide, so I wanted to ask if you ever created it by chance?

**Comment by hscumbie** [comment]
> Hi! I just wanted to ask if you ever made that YouTube video by chance? I'm having the same problem and it sounds like you have a really good step-by-step guide, so I wanted to ask if you ever created it by chance?

Apologies. I got busy with life and simply forgot. I also bought a new MacBook and haven't had the need anymore for a macOS Virtual Machine. 

However, I'll get something made up here within the next few days and get it posted. The process is pretty simple, and should still work regardless. Please ping this thread if nothing comes out in the next week!

**Comment by hscumbie** [comment]
Decided it would be easier to make a text version of a How-To for enabling JIT instead.

**Disclaimer**: This guide is for how to get around the `The URL to download the Developer Disk image could not be determined` error. This ultimately stems from not having an up-to-date Xcode (which in turn requires a Mac that supports the latest Xcode...)

### How To Create/Install macOS Virtual Machine

**Important: Only macOS 12 and newer will work. macOS 11 is unsupported by VMware Fusion**
**Important 2: At least 50 GB of free storage will be needed to get this working. Virtual Machines require lots of space**

### Section 1: Downloading and creating a macOS ISO

1.  Go to the App Store on your Mac and download a copy of macOS (I recommend Ventura as it is the most problem free)
<img width="1292" alt="Screenshot 2024-04-26 at 1 25 13 PM" src="https://github.com/altstoreio/AltStore/assets/93226094/cb66b0bd-af4b-493f-9b44-24f21c39db5b">

2. Once the macOS installer is done downloading, open a terminal window. At this point, we're creating a blank space for the ISO to reside on your disk. You will need at least 16GB of free space. 
<img width="842" alt="2" src="https://github.com/altstoreio/AltStore/assets/93226094/ca7b9543-74f8-4d82-99ef-95fef3e855f1">

3. Execute this command to create the DMG file:
```
hdiutil create -o /tmp/Ventura -size 16384m -volname Ventura -layout SPUD -fs HFS+J
```
<img width="842" alt="3" src="https://github.com/altstoreio/AltStore/assets/93226094/0255a7c4-b9f2-46cb-bce0-dc0134a66378">

4. Now mount the DMG file using this command:
```
hdiutil attach /tmp/Ventura.dmg -noverify -mountpoint /Volumes/Ventura
```
<img width="842" alt="Screenshot 2024-04-26 at 1 41 24 PM" src="https://github.com/altstoreio/AltStore/assets/93226094/d938e163-5540-4615-93dd-6c24462379ef">

5. Now we're going to use the `createinstallmedia` application that comes with the macOS installer. Execute the following command to create the installation media on the DMG file (This will require an admin password so have that handy):
```
sudo /Applications/Install\ macOS\ Ventura.app/Contents/Resources/createinstallmedia --volume /Volumes/Ventura --nointeraction
```
<img width="842" alt="5" src="https://github.com/altstoreio/AltStore/assets/93226094/d56f06d5-f65c-44f7-870a-049465c191b7">

6. Once the `createinstallmedia` has finished running, detach the image by executing 
```
hdiutil detach /volumes/Install\ macOS\ Ventura
```
<img width="842" alt="6" src="https://github.com/altstoreio/AltStore/assets/93226094/625e3472-b8d7-45e7-9c39-5b3e316b6511">
7. Now we're going to start the process of converting the DMG file into an ISO. First, execute this command to create a CDR file from the DMG:

```
hdiutil convert /tmp/Ventura.dmg -format UDTO -o ~/Desktop/Ventura.cdr
```
<img width="842" alt="7" src="https://github.com/altstoreio/AltStore/assets/93226094/92c416f9-a497-45a3-8d9c-14fdbae11c72">

8. The final step to this section is to change `Ventura.cdr` to `Ventura.iso`. This is done by executing:
```
mv ~/Desktop/Ventura.cdr ~/Desktop/Ventura.iso
```
<img width="842" alt="8" src="https://github.com/altstoreio/AltStore/assets/93226094/ed95fad2-2115-4f3b-b774-0ce188c20a77">

**Note: It is recommended to reboot your Mac after this section. The `/tmp` directory gets purged each time you reboot. This will give you back some needed space.**

Section 2 to follow.

**Comment by Astal08** [comment]
> Section 2 to follow.
Hi, sorry for the bother, but when could you write section 2? I’m new to the whole side loading thing. Thanks in advanced.

**Comment by hscumbie** [comment]
### Section 2: Downloading VMWare Fusion Pro 

1. Now that an ISO image of macOS has been made, it is now time to download, install, and license VMWare Fusion. Navigate to [this page](https://blogs.vmware.com/teamfusion/2024/05/fusion-pro-now-available-free-for-personal-use.html) to download the app (Note: you will need to make a Broadcom account and fill out their information in order to download the application).

<img width="1512" alt="Screenshot 2024-05-14 at 7 50 35 PM" src="https://github.com/altstoreio/AltStore/assets/93226094/e40e35e5-9746-41eb-b6db-36d177e6df95">

<img width="1512" alt="Screenshot 2024-05-14 at 7 52 37 PM" src="https://github.com/altstoreio/AltStore/assets/93226094/c9bbc113-2ea0-4a65-8bd1-c4c3bca9664d">


2. Install the software by double clicking the icon
<img width="812" alt="Screenshot 2024-05-14 at 7 54 06 PM" src="https://github.com/altstoreio/AltStore/assets/93226094/627eb985-c4d0-4f36-b7aa-0c79f9ccfe1a">

3. Follow on-screen install instructions

### Section 3: Installing the macOS Ventura Virtual Machine

1. Launch VMWare Fusion
2. Use [this link](https://docs.vmware.com/en/VMware-Fusion/13/com.vmware.fusion.using.doc/GUID-B7A0B805-BFEA-4BD3-99D8-A914897D7C36.html#GUID-B7A0B805-BFEA-4BD3-99D8-A914897D7C36) to create a macOS virtual machine from the ISO we just created (I apologize. at the time of writing this, it seems ARM based Macs don't allow for creating macOS virtual machines. I can't give a detailed walkthrough on this portion)
3. Once the virtual machine is installed, download AltStore and follow the same instructions in the FAQ for enabling JIT.


Once again, I apologize for not being able to write a fully complete guide. I'll do my best to answer any questions based on the experience I had on my old 2017 MacBook Air. Please post questions with screen captures here so others can see as well.

Thanks!

**Comment by MochyPei** [comment]
What i need to do if i have only one pc on Windows? (iPhone 11 iOS 17)

**Comment by pgbsean** [comment]
> What i need to do if i have only one pc on Windows? (iPhone 11 iOS 17)

hackintosh it :(
