### ISSUE TITLE
Lost connection to AltServer

### ISSUE THREAD

**Issue by meieri** [rileytestut/AltStore#22]
Cannot download Delta or AltStore update from AltStore app. Both apps get to about 2/3rds downloaded and then the "lost connection to AltServer" notification pops up. iPhone 6s running iOS 13.1, AltServer running on MacOS 10.14.6

**Comment by DanielBrierton** [comment]
I was getting the same error, but it worked fine when connected by USB. Discovered Wi-Fi Sync wasn't enabled. Try enabling it and see if that sorts your problem.

Here's instructions on how: https://support.apple.com/en-ie/HT201253

**Comment by 1337N0013** [comment]
How do you enable just Wi-Fi Sync on macOS 10.15 with the new Finder? I don't want to sync my music or photos or anything else. I've selected `Show this iPhone when on Wi-Fi`, but the same problem occurs. I've deselected all the sync options aside from that, and there is no sync option for the Files tab.

**Comment by ifyour** [comment]
Connecting USB can work normally. 😻

**Comment by dontbanmeplz** [comment]
#123

**Comment by noah978** [comment]
This issue should be fixed in the latest versions of AltStore/AltServer. Closing this issue now.

**Comment by aadesousa** [comment]
> 
> 
> This issue should be fixed in the latest versions of AltStore/AltServer. Closing this issue now.

I'm still experiencing this on ios 13.3 when installing apps from files

**Comment by hsusanoo** [comment]
Same issue here with Altstore v1.4.3 and ios 14.5

**Comment by metalzero24** [comment]
While installing some apps, this happens with latest versions for me too. Can provide .ipa file if needed.

**Comment by Noxillio** [comment]
Same problem here. Why does anyone suggest this software when it doesn't work and gets no attention from the developer anymore anyway? With all due respect, I love Riley's work, but holy shit this is ridiculous.

**Comment by FlowingMercury** [comment]
I am also having this issue. iPhone XR on iOS 14.5.1

**Comment by Rexexe** [comment]
Same issue here with IPhone 13 on ios 15.4,window11,Altstore v1.5.0.0

**Comment by shampoolegs** [comment]
I'm currently having this issue on windows. App starts to install, one app asks if I want to allow additional permissions and then suddenly loses connection.
