### ISSUE TITLE
AltStore does not give apps an icon on iOS 14

### ISSUE THREAD

**Issue by DumbGameMaker** [rileytestut/AltStore#355]
**Describe the bug**
When you sideload an app, it won't have an icon. I tried with 2 different .ipa's and none of them had one. Delta and Clip had one though.

**To Reproduce**
1. Download an ipa
2. Sideload the ipa
3. Find your sideloaded app
4. it has a white box as an icon...

**Expected behavior**
Apps should have icons.

**Screenshots**

**Desktop (please complete the following information if applicable):**
 - OS: [Mac or Windows] iOS 
 - Version: [e.g. Catalina] 14.0

**iPhone (please complete the following information):**
 - Device: [e.g. iPhone8] iPhone11,8
 - iOS: [e.g. 13.1] 14.0

**Additional context and logs**
Add any error logs or any other context about the problem here.

**Comment by lonkle** [comment]
This has been fixed in the beta (or in the alpha branch, can't remember). Well, I shouldn't say fixed since those IPAs very likely didn't have icons in the first place (lots of sideloaded IPAs don't by default), but you can change your custom icon at anytime now (or add one in case the icon is blank / white). So those white icons, just download a png and long press on the app in AltStore and select Choose Icon Image and 💥. I'll update this issue when this feature rolls into the stable release.

**Comment by DumbGameMaker** [comment]
gotcha, thanks

**Comment by firofame** [comment]
I still have this issue in AltStore 1.4.5, iPhone 11, iOS 14.4.2

**Comment by lonkle** [comment]
@firofame Go to AltStore's My Apps page, hold down the app that is missing an icon and click "Change Icon" to give it (or any app) any icon you'd like.

**Comment by Gamertron300** [comment]
@lonkle This option is not available on the current version of the app.

**Comment by rayvearn** [comment]
still have this issue on ios and ipados 15 with the latest altstore/server beta
