### ISSUE TITLE
AltStore App Sign In With Apple Id Infinite Loop

### ISSUE THREAD

**Issue by ShikoiKurogami** [rileytestut/AltStore#96]
AltStore(Windows Version)
When attempting to sign in with Apple Id*, the Sign In Button will infinitely loop after inputting Apple Id and Password, never logging in, making the app unable to sign in. The App does NOT crash when doing this.

*iPhone XR, iOS 13.3, Connected to PC, On Same Wifi

**Comment by C0braD3v** [comment]
Can reproduce this, MQAR2LL/A (iPhone X) iOS 13.3.1

**Comment by Mooonblaze** [comment]
Me as well. iPhone 8, iOS 13.3.1, though it did the same exact thing somewhere on iOS 12 before I updated to try again. App-specific password, regular password, nothing. It loads forever, and I am given no prompts or error messages.

**Comment by C0braD3v** [comment]
This is most likely caused by iOS 13.3.1
 Provision verify

**Comment by C0braD3v** [comment]
Seems like this issue has been fixed, no longer getting the issue.

**Comment by devwearsprada** [comment]
I am still having this issue. iPhone XR on IOS 13.3. After putting in my Apple Id it keeps loading infinitely, no crashes, no error messages.

**Comment by C0braD3v** [comment]
After multiple trials on devices, this issue is not longer occurring as stated previously. Make sure to attempt reinstalling. If the issue is resolved, please close it.

**Comment by apivovarov** [comment]
AltStore 1.4.4, iphone 6, iOS 12.5.1

Sign in with Apple ID hangs (the wheel is turning and turning)

It does not matter if I enter correct or wrong password.

Looks like it can not reach apple id server.

**Comment by buffalodragon** [comment]
Still occuring, iPad OS 18
